project:
  type: book

book:
  title: "sol_6cha1"
  author: "Jane Doe"
  date: "2023. 10. 11."
  chapters:
    - index.qmd
    - intro.qmd
    - plusfile.qmd
    - sol_7.qmd
    - sol_10.qmd
    - sol_11.qmd
    - sOl_13.qmd

bibliography: references.bib

format:
  html:
    theme: cosmo
  pdf:
    documentclass: scrreprt

editor: visual

