project:
  type: book

book:
  title: "sol_6cha1"
  author: "Jane Doe"
  date: "2023. 10. 11."
  chapters:
    - index.qmd
    - intro.qmd
    - plusfile.qmd
    - The Divided Mind.qmd
    - Us and Them.qmd
    - Get Curious.qmd
    - Storytelling.qmd
    - Navigating Conflict.qmd
    - Comment.qmd

bibliography: references.bib

format:
  html:
    theme: cosmo
  pdf:
    documentclass: scrreprt

editor: visual

