# Comment

## 이 강의를 듣고서

자주는 아니지만 종종 뉴스를 봅니다. 기사를 읽다보면 다른 사람의 의견도 궁금해져서 종종 댓글을 보는데 그러다보면 제 생각과 전혀 일치하지 않아서 '왜 이렇게 생각하는 거지?'라는 의문에 빠집니다. 왜냐하면 누가봐도 제 의견이 옳고, 정당하다고 느끼기 때문입니다. 그래서 저와 다른 의견을 가진 사람들은 틀리고, 잘못된 생각을 가진 사람들이라고 판단하곤 합니다.

하지만 이 수업을 들으며 항상 그렇지만은 않다는 것을 깨달았습니다. 'Us and Them' 단원에서 민주당이나 공화당이든 지지 정당은 달라도 총기 규제나 낙태 문제에 대해 똑같이 고민하고, 옳지 않은 일이라고 생각한다는 설문 조사를 보며 문제에 대해 적용되는 도덕 기준이 다를 뿐이라는 것을 알게 되었습니다. 이런 부분을 통해 평소에 제가 얼마나 편협하고 극단적인 가치관을 가지고 있는지에 대해 느끼게 되었습니다.

특히 총기 규제에 대해 새로운 관점을 가지게 되었습니다. 한국은 총기 소지 자체가 불법이기 때문에 총기를 들고 다닌 다는 사실 자체에 부정적이지만, 미국은 수정 헌법 2조에 총기 소지에 대한 자유가 명시되어 있을 정도로 이 문제에 대한 개인의 선택을 존중합니다. 그렇기에 총기가 만연한 만큼 다른 사람들도 가지고 있는데 본인이 들고 있지 않는다는 불안함이 존재하기에 개인을 보호하기 위해 어떤 점에선 총기 소유가 필수불가결하단 걸 알게 되었습니다.

그렇다고 해서 총기 소지에 대해 찬성하는 것은 아닙니다. 여전히 총기 소지는 불법으로 정해야 하고, 국민이 총기를 소유하는 건 지나치게 위험하다는 생각은 변하지 않았습니다. 하지만 어떤 이들에게 총기 소지가 어쩔 수 없이 필요할 수 있다는 점은 이해하게 되었습니다. 이런 과정을 통해 상대의 입장을 이해해보려는 '탐험가적 마인드'의 중요성에 대해 느낍니다. 상대의 입장을 이해하기 전의 저라면 아마도 총기 규제는 절대적으로 나쁜 것이라며 '싸움꾼의 마인드'로 상대방의 의견을 들어볼 생각도 하지 않고 의미 없는 논쟁을 하게 될 것입니다. 하지만 상대를 이해하고 있는 저는 '탐험가적 마인드'로 상대를 이해하며 상대에게 공감하며 '논쟁'을 위한 대화가 아니라 '설득'을 위한 대화로 더 나은 결과를 얻을 수 있을 것입니다.

상대방의 의견은 '다른'것이지 '틀린'게 아니다는 것을 진심으로 이해하는 건 매우 어려운 일입니다. 특히 저는 한 가지를 결단 내리면 다른 사람이 반대해도 그대로 밀고 나가는 경향이 있기 때문에 더욱 그렇습니다. 그렇기에 저는 상대를 이해하고 제대로된 대화를 진행하기 위한 이번 수업이 매우 좋은 기회가 되었으며 앞으로 이런 부분을 실생활에서 실천하기 위해 노력할 것입니다.
