---
title: "Navigating Conflict"
---

## Our Brains on Panick

-   우리의 뇌는 쾌적한 존, 스트레치 존, 패닉 존으로 나뉜다. 이 중에서 패닉 존에 있을 때 우리는 아래와 같은 반응을 보인다.

-   전투/도피/경직 반응 : 우리가 공황상태에 있을 때, 혹은 위협을 감지했을 때.

    -   전투 = 논쟁 또는 변호

    -   도피 = 회피 혹은 철수

    -   침묵 = 소극적 응답 혹은 조치 실패

## 100% Elephant

-   코끼리(감정)이 날뛰는 패닉존에 있을 땐, 코끼리를 스트레치존으로 데려가야 한다.

## Detect - Pause - Redirect

-   패닉 상태임을 인지해라.

-   일단 잠깐 멈춰라

-   패닉존에서 벗어날 길을 찾아보자.

### 1. Detect

-   작 자신이 패닉 존에 있는지 확인한다. 아래와 같은 반응이 있다면 패닉 존에 있다는 걸 알 수 있다.

    -   Physical Sign: 얼굴 후끈, 덥거나 춥고, 손발이 차가워진다면?

    -   Thoughts: 난 바보야 ... 난 끝났어 ... 생각이 든다면?

    -   Emotions: 불안, 좌절, 죄책감이 든다면?

    -   Behaviors: Fight(공격, 비난), Flight(회피), Freeze(조용히) 한다면?

### 2. Pause

-   공황구역에 댛나 반응을 늦춘다.

    -   일단 잠깐 멈추고, 심호흡 !!!!!! (1, 2, 3)

    -   너의 감각을 사용해서 현재의 상황을 둘러봐.

    -   주변에 대한 판단 대신, 너의 현 상황에 집중해봐.

    -   너 스스로와 긍정적인 대화를 해봐. 넌 할 수 있어, 잘했어 등.

### 3. Redirect

패닉 존을 떠나는 경로를 설정한다.

-   역할을 소유하고 관심을 표현한다.

    -   자신의 언행에 책임을 진다. "나는 내가 \~한 적이 있다는 것을 인정한다."

    -   누군가에게 당신들의 관계나 공동의 목표를 공감하거나 일깨워주다. '정말 우울해보여요. 다인의 생각을 더 공유할 수 있을까요?'

-   문제를 해결하다

    -   행위 : 어떤 사람의 행동을 해석한다.

    -   영향 : 행동이 당에게 미친 결과

    -   요구 사항 : 그들엑서 무엇을 얻을 필요가 있는가?

-   휴식하기

    -   대화를 잠시 중단합니다. '지금 대화해도 도움이 될 것 같지 않다. 조금만 있다가 다시 얘기하자.'

### Take a break

-   패닉 존에 있다면, 멈추고 다시 얘기해보자
