# Sol_13주차

# Let's Find someting to Talk About

이야기가 같고 있는 힘. 그냥 말하는 것보다 한 사람이 자신의 이야기리를 예시로 들며 상대방을 설득하자 더 설득이 잘 되었다.

# The Anatomy of a Story

목적에 맞는 이야기를 쓰면 상대방은 잠재적으로 주제에 더 집중하고 이해해준다. 눈 앞에 있는 상대방과 연결고리가 있기 때문이다.

우리가 이야기를 할 때는 3가지를 고려할 것

1\. 진정성이 있어야 한다. - 그 솔직함이 상대방을 공감할 수 있게 한다. 진실을 통해 감정(두려움, 행보그 믿음, 분노)을 공유할 수 있어야 한다.

2\. 중요성 : 말하는 이야기가 상대방에게 중요한 이야기여야 한다.

3\. 요점 : 이야기로 끝나지 않고 요점이 있어야 한다.

# There's a stroy For Everthing

By now you might be thinking, "Do I need a story for everything I believe? Can't I just believe something without having direct personal experience to back it up?"

 

Great question!

 

We often have strong feelings about issues without really thinking about what's driving them. But when you take the time to think about it, there's a reason why you feel the way you do about an issue. And that reason is usually connected to a story, even if it's not your own firsthand experience. As long as a story is rooted in your own values, emotions, and beliefs, it can be compelling to anyone listening.

# Secondhand Stories

: 간접적인 이야기

자신이 직접 경험하지 않은 다른 사람의 이야기로 영향을 받는다.

심경의 영향을 준 뉴스 스토리 : 총격 사건으로 14살 아들을 잃은 부모의 얘기를 본 후 총기 사건이 일어나선 안 된다고 생각하게 되었다. -\> 타인의 얘기를 듣고 신념이 변하게 된 예시

-   가족의 신념 : 자신의 할머니와 굉장히 친했다. 할머니는 종교인이고 모든 인간의 순결함을 굉장히 우선시하는 의사다. 그녀는 거의 5주동안 심장 박동을 가지고 있다고 얘기했고, 그 얘기를 들었을 때 자신이 종교인은 아니지만 낙태에 반대해야 겠다고 생각했다. -\> 가족의 신념이 전이된 예시

-   친구&지인의 얘기를 통해 신념이 형성된 사례 : 에콰도르에서 이민을 온 룸메이트가 있었음. 불법이민 신분이기에 시민권도 못 따고 생활에 불편한 점이 많았음. 이런 얘기를 듣고 이민자들이 시민권을 갖는 게 얼마나 중요한 것인지 알게 되었다고 한다.

-   대중적으로 유명한 사람이 영향을 준 사례 -\> 존경하는 작가가 아팔레치아(미국에 있는 산맥)에서 자란 아이에 대한 이야기를 씀. 기후변화로 인해 아팔레치아 사람들이 일자리를 잃게 되었다는 걸 알게 되고 기후변화에 대해 부정적인 시각을 갖게 되었다.

# The Burden of Stories

-   이야기를 할 때 자신이 너무 불편한 상황까지는 부딪힐 이유는 없다.

-   하지만 이야기를 할 수 있는 능력을 키우는 건 중요하다.

    -   이는 건설적 대화를 하는데 굉장히 중요한 능력이기 때문이다.

    -   우리는 얼마든지 이야기를 하는 능력을 갖출 수 있다.

-   쉽지 않지만 이야기를 할 줄 아는 건 여러분의 삶에 굉장히 도움이 될 것이다.

# Responding to Stories

-   이야기를 하는 건 중요하지만 다른 사람의 이야기를 듣는 것도 중요하다 -\> 하지만 실천하는 건 말만큼 쉽지 않다

-   다른 사람한테 자신이 경청하고 있다는 걸 표현하는 것 또한 중요하다

    -   인정 : 들었을 때 잠깐 멈추고 첫 반응을 제시하고 감탄하는 것.

    -   미러 : 말한 것을 그 사람에게 말해줘라. 상대가 말을 듣고 있다는 걸 알게 해 준다.

    -   재진술 : 상대가 말한 것의 가치와 감정을 읽어서 이를 다시 말해주는 것.(미러와 다르다고 생각해야 함)

        -   언제 어디서나 총기를 얻을 수 있어야 한다고 생각해 -\> 넌 가족의 안전과 보호에 관심이 많구나. 그래서 총기를 사용하려는 자유를 중요하게 여기는 구나.

    -   공감 : 똑같은 방식으로 느끼지 않더라도 상대방이 느낀 것을 같이 느끼려고 노력하는 것

# Life Hack

-   이야기를 할 때 직접 연습을 해 봐야 한다. 그들의 이야기를 해보라고 한 후 듣는 연습을 해야 한다.

    -   정직, 중요성, 요점을 기억할 것

# Lesson 4 Recap

-   이야기는 사람들의 직관을 끼어들어서 상대가 수용적으로 받아들이도록 도와준다.

-   이야기는 솔직해야 하고, 중요해야 하고, 요점이 있어야 한다. 직접적인 경험없이 간접적인 경험만으로도 충분하다.

-   이야기를 듣고 반응하는 것 또한 상대에게 많은 영향을 주기 때문에 중요하다

# Lesson 5 : Navigating Conflict

## 100% Elephant

-   코끼리(감정)이 날뛰는 패닉존에 있을 땐, 코끼리를 스트레치존으로 데려가야 한다.

## Detect - Pause - Redirect

-   패닉 상태임을 인지해라.

-   일단 잠깐 멈춰라

-   패닉존에서 벗어날 길을 찾아보자.

### 1. Detect

-   Physical Sign: 얼굴 후끈, 덥거나 춥고, 손발이 차가워진다면?

-   Thoughts: 난 바보야 ... 난 끝났어 ... 생각이 든다면?

-   Emotions: 불안, 좌절, 죄책감이 든다면?

-   Behaviors: Fight(공격, 비난), Flight(회피), Freeze(조용히) 한다면?

### 2. Pause

-   일단 잠깐 멈추고, 심호흡 !!!!!! (1, 2, 3)

-   너의 감각을 사용해서 현재의 상황을 둘러봐.

-   주변에 대한 판단 대신, 너의 현 상황에 집중해봐.

-   너 스스로와 긍정적인 대화를 해봐. 넌 할 수 있어, 잘했어 등.

### Take a break

-   패닉 존에 있다면, 멈추고 다시 얘기해보자
