# sol_11주차

# Get Curious

-   우리가 어떤 대화를 할 떄 논쟁적인 부분에서 탐색하려는 부분이 필요할 것이다. 서로 연결하고 이해하려는 부분으로 바꿀 수 있는데 이걸 탐험가적 마음가짐이라고 한다.
-   이런 탐험가적 마음가짐을 통해 논쟁을 이해하고 상호작용하는 게 목표

# Warrior Mindset

-   같은 도덕 기반을 갖고 있지만 우리는 종종 특정한 가치만이 옳다고 생각할 수 있다. 그 결과 서로 의견 불일치가 생긴다.
-   이기고 지는 경쟁관계가 되면 제로섬 관계가 된다. 이런 싸움꾼의 마음가짐으로서는 이기는 마음가짐만 있고 듣는 것이 이뤄지지 않는다.

# Warriors Lose

-   이기면 기분은 좋겠지만 이건 안 좋은 결과로 이끈다.'
    -   다른 한 쪽을 방어적인 쪽으로 이끌거나

    -   공격/모욕/위협 받는 것처럼 느껴지게 한다.

    -   그 사람과의 관계는 손상된다.

        -\> 싸움꾼의 마인드 셋은 별로 안 좋다는 것을 알 수 있다.

# Being Wrong

-   모든 사람들은 내가 옳다는 느낌을 받고 싶어하고, 자신이 틀리다는 느낌을 싫어한다.

-   우리는 가끔씩 틀리는데 그런 느낌을 받지 못했을 때 틀린다.

# 설명 깊이의 착각

-   우리는 어떤 기계의 작동 원리를 잘 알고 있다고 착각함.

-   세상의 복잡한 쟁점에 대해서는 자신이 잘 안다고 생각하지만 실제로는 그렇지 않다

-   설명하다 보면 내가 생각보다 잘 알고 있지 않다는 것을 알 수 있다

# Embracing Not Knowing

-   우리는 실제로 잘 알지 못하지만 그 쟁점에 대해 강한 인상은 있다.
-   설명 해 보라고 했을 때 우리는 이걸 잘 알고 있지 못하다는 걸 알 수 있다. 그런 사실을 알고 있는 게 굉장히 건강한 일이라는 걸 알 수 있다.

# Intellectual Humility

-   우리가 알고 있는 것에 한정되어 있고, 자신이 틀릴 수 있다는 걸 인정하는 게 굉장히 중요하다 이런 걸 '지적 겸손'이라고 한다.
    -   내가 틀렸다는 걸 받아들이는 게 삶의 이유다

    -   비판을 잘 받아들일 수 있어야 함.

    -   자신이 틀리는 걸 자신의 성장 기회로 봄

# Belief Updating

-   흑백논리에 있지만, 그 중간에 있을 순 없을까?

    -   내가 전부 다 틀린게 아니라, 내 확신을 새로운 사실 혹은 근거에 의해 확신도를 떨어트린다면 !

-   Belief Updating = 생각을 / 신념을 업데이트!

# Changing Your Mind

-   내 신념을 업데이트 할 수 있는 마음가짐을 가지고 있는 것이 중요함.

-   탐험가의 마음가짐이 필요. '열린 마음'

# Explorer Mind

-   Curious: 호기심을 가져라.

    -   무조건적인 반박 X. 니가 왜 그런 생각을 하는지 궁금해. 왜 그 사람들은 늘 그렇게 느끼는걸까?

-   Good Q: 좋은 질문을 해라

    -   남을 판단하고 공격하는 질문은 하지 마라! 넌 잘 몰라 이런 뉘앙스. 조언식의 질문.

# Constructive Questions

-   **Are Genuinely Curious: 니가 정말 궁금해하는 거냐**

    -   진정 궁금한거냐? 알고싶어하는 진실된 마음.

        -   니가 그 말 했잖아. 그 말이 무슨 의민지 나한테 좀 더 얘기해줄래?

-   **Are open-ended: 열린 질문**

    -   간단하게 예스/노로 대답 가능한 질문 말고! 왜 그런거야? 어떻게 그렇게 된거야? 같은 열린 질문을 해라

-   **Invite complexity: 복잡한 내용을 준비해라**

    -   중간지점인 흑백지역(복잡한 지점)을 나눠라.

        -   넌 늘 이런식으로 느꼈니? 널 헷갈리게 하는 요소는 없을까?

-   **Invite stories: 이야기를 끌어내라**

    -   사실과 숫자에 대한 이야기 대신 그 사람에 관한 이야기를 해라.

        -   널 그렇게 믿도록 한 너의 삶에 대해 얘기해줄래? 왜 그런 믿음을 가지게 된거야? 스토리를 공유하게끔.

-   **Use a curious tone: 궁금증의 톤을 갖고 있어라.**

    -   판단하고 비난하는 듯한 톤이 들어가지 않도록 유의. 호기심 가지는 톤!

## Life Hack

Try using the questions below to guide you:

-   Why is this issue important to you?

    -   이게 너한테 왜 중요해?

-   Can you tell me more?

    -   더 자세히 말해줄래

-   Can you share more about what you mean when you say

    -   니가 말한거 뭔 뜻인지 좀 더 말해줘

-   Why do you think that is?

    -   왜 그렇게 생각하는거야?

-   Can you share something about your experience that may have led you to believe ?

    -   이런 생각을 가지게 된 니 경험을 말해줘

-   Is there anything about where you feel conflicted or pulled in two different directions?

    -   복잡하다거나 방향성이 안 맞는 경우는 없었을까? (모순점, 충돌점)

-   What is at stake for you or someone you know about this issue?

    -   이 쟁점에 관련된 이해관계는 없니?

-   Why do you think you care so deeply about this issue?

    -   이 쟁점에 깊이 관여한 이유는 뭐야?

-   Have you always felt that way?

    -   넌 늘 그렇게 생각하는거야?

JH\> 남을 판단하는 질문 자제. 그 의견을 가지는 이유는 뭘까? 물어봐야지
