# sol_10주차

# Us and Them

-   정치적인 신념, 도덕적인 차이는 어디에서 오는가

# Let's Recap

-   이중 처리 : 우리의 뇌에는 직관과 추론 영역이 있다.

    -   직관 : 자동적이고, 빠르고, 의식적이며, 감정적이다

    -   추론 : 느리고, 의식적이며, 노력해야 하고, 논리적이다

    -\> 우리의 직관이 추론을 이끈다.

# Mind Reading

-   정치적 분열에서 코끼리와 탑승자가 어떻게 작동하는지 알아볼 것이다.

# What do Republicans Believe?

-   공화당을 믿는 사람들은 어떻게 생각하는가.

# How We See Each Other

-   설문조사 자료를 통해 반대편에 있는 사람들도 똑같이 인종차별, 성차별, 총기규제 문제에 대해 걱정하고 있다.

# The Perception Gap

-   타인의 실제 신념과 내가 인식하고 있는 그 사람의 신념은 큰 차이가 있다. (인지 차이)

-   거의 모든 사람들이 이러한 인지 차이가 있다.

-   이런 인지 차이는 다른 사람과 얼마나 많은 상호작용을 하느냐에 따라서 인지 차이에 영향을 받는다.

# What Creates the Perception Gap

1.  에코 룸 : 비슷한 사람들끼리 상호 작용하면 그 사람들끼리 상호작용하며 생각이 점점 강해져서 그 공동체와 다른 공동체와 성격이 분리됨
2.  극단적인 관점이 제일 커진다 : 극단적이고 자극적인 이슈가 미디어에서 주목받는다. 그래서 정치적 견해는 이런 양극단이 될 수 밖에 없다.

# The Implications

-   우리가 쉽게 생각한 것만큼 나뉘어져 있진 않다.

-   실제로, 섭외한 67%의 미국인들은 이런 극단적인 정치 양극화에 지쳐 있다고 하기도 했다.

# Where Do Our Differences Come From?

-   도덕기반이론: 우리의 마음은 6가지의 맛을 느끼는 혀와 같다. 세상에 대해 옳고 그름을 판단하는 기준이 6가지가 있다는 뜻.

    -   우리가 맛을 느끼는 체계는 같지만, 각자의 삶의 배경이 다르므로 우리가 맛을 느끼는 정도도 다 다르다

-   돌봄, 공평, 자유, 충성, 권위, 순결

# Our Moral Intuitions

-   코끼리가 걸러낸 것으로 라이더가 결정을 한다.

-   우리가 세상에 대한 정보를 처리할 때 코끼리가 가지고 이쓴 도덕 직관 필터로 세상을 이해한다.

-   우리가 미디어를 접할 때 코끼리의 도덕 직관으로 순식간에 필터를 거친다. 이 과정은 정확한 정보를 알기도 전에 이루어진다.

    -   그만큼 도덕직관은 강력하게 우리를 이끈다.

# Uncovering the Moral Foundations

## care

-   돌봄 기반 : 다른 사람을 돌봐주는 것, 위해를 끼치는 것을 막는 것 도덕 기반을 우선시하는 사람들은 공감, 친절함을 우선시한다.

## Faimess

-   공평: 모두가 공평하게 대접받길 원하기에 사기꾼을 싫어한다. 그리고 직접 속인 사람이 아니더라도 속임수를 싫어한다. 이 공평 기반은 정의, 공평, 상호성을 중요시한다.

## liberty

-   자유 : 개인의 자유에 대한 이상, 압제에 대한 반대가 높다.

## loyalty

-   충성 : 내집단에 대한 충성. 윗사람에 대한 충성이 아님. 소속감에 가까움

## authority

-   권위 : 합법적인 것, 전통에 대한 존중.

## sanctity

-   성스러움 : 순결하거나 신성에 대한 것. care와는 구분됨. care는 위해를 끼치는 것에 대한 거부. 근데 sanctity는 깨끗한 것, 순수한 것, 순결한 것에 대한 욕망이 있다.

-   대표적으로 종교, 자연, 사람의 몸같은 것을 의미.

# Why We Disagree on Right and Wrong

-   우리의 도덕 기반은 우리의 믿음을 이해하는데 도움이 되지만 우리가 왜 정치적으로 다른 견해를 가지는지도 이해할 수 있다.

-   보수적인 사람과 진보적인 사람은 서로 중심으로 두는 가치가 다르다.

# Decoding Language

-   왜 우리가 서로 다른 도덕적 기반을 가지고 있는가에 대한 것

# Same Foundations, Different Applications

-   둘은 같은 기반을 사용하지만 서로 다른 방법으로 그걸 이슈에 적용했다.

-   에이샤는 총기 규제에 대해선 자유를 주장했지만 낙태를 반대할 땐 자유를 주장하지 않았다.

-\> 이슈에 대해 도덕 기반을 적용하는 종류는 같을 수 있어도 적용 대상은 다를 수 있다. - 관점이 크게 다른 것 같지만 크게 다르지는 않다

# 결론적으로

-   반대 의견도 들어보면서 극단적인 사람이 되지 않기 위해 노력해야 한다.

# Recap

-   우리는 다른 측면을 실제보다 더 극단적인 것으로 생각한다.
-   우리는 6가지 도덕 기반을 전부 갖고 있다.
-   삶의 경험은 우리의 도덕적 관점을 형성하는데 굉장히 큰 역할을 한다.
-   보수와 진보는 이런 방법의 다른 방법, 정도로 도덕 기반에 의지한다.
-   우리는 사람의 언어를 통해서 그 사람들이 믿고 하는 것에 대해 해독할 수 있다.
